services:
  thereiwas_database:
    container_name: thereiwas_database
    image: postgres:17-alpine
    volumes:
      - ./volumes/thereiwas_database:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=thereiwas
      - POSTGRES_PASSWORD=debugpassword
      - POSTGRES_DB=thereiwas
    restart: "unless-stopped"
    ports:
      - "5432:5432" # just needs to be exported for debugging purposes
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U thereiwas" ]
      interval: 10s
      timeout: 5s
      retries: 5