name: "Release: Backend"
on:
  push:
    tags: 'backend-[0-9]+.[0-9]+.[0-9]+'
env:
  VERGEN_IDEMPOTENT: false

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract meta data for the docker container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/flying7eleven/thereiwas-backend
          tags: |
            type=match,pattern=backend-(\d+.\d+.\d+),group=1
            type=match,pattern=backend-(\d+.\d+),group=1
            type=match,pattern=backend-(\d+),group=1

      - name: Build and push Docker image (thereiwas-backend)
        uses: docker/build-push-action@v5
        with:
          context: thereiwas-backend
          file: thereiwas-backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
