name: "Build: Backend"
on:
  push:
    branches: [ main ]
    paths:
      - 'thereiwas-backend/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - run: sudo apt-get install -y libpq-dev
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            thereiwas-backend/target/
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add rustfmt
      - run: cargo build --verbose
        working-directory: thereiwas-backend
      - run: cargo fmt --all -- --check
        working-directory: thereiwas-backend
      - run: cargo test --verbose
        working-directory: thereiwas-backend
