name: Build thereiwas-frontend
on:
  push:
    branches: [ main ]
    paths:
      - 'thereiwas-frontend/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install the dependencies
      run: npm ci --legacy-peer-deps
      working-directory: thereiwas-frontend
    - name: Build the frontend
      run: npm run build
      working-directory: thereiwas-frontend
    - name: Run tests
      run: npm run test
      working-directory: thereiwas-frontend
